<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128512;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128513;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128514;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128515;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128516;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128517;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128518;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128519;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128520;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128521;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128522;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128523;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128524;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128525;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128526;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128527;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128528;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128529;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128530;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128531;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128532;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128533;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128534;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128535;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128536;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128537;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128538;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128539;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128540;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128541;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128542;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128543;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128544;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128545;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128546;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128547;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128548;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128549;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128550;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128551;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128552;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128553;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128554;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128555;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128556;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128557;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128558;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128559;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128560;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128561;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128562;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128563;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128564;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128565;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128566;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128567;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128577;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128578;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128579;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#128580;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129296;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129297;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129298;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129299;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129300;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129301;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129312;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129313;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129314;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129315;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129316;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129317;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129319;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129320;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129321;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129322;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129323;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129324;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129325;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129326;</span>
<span style="font-size:32px;" onclick="$j('#chat-message').val($j('#chat-message').val()+ $j(this).html());">&#129327;</span>